modLoader="javafml" #mandatory
loaderVersion="[38,)"
license="All rights reserved"


[[mods]] #mandatory
modId="metalbushesmod" #mandatory
version="1.18-2.10" #mandatory
displayName="Metal Bushes" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks to early Tinkers Consturct!" #optional
authors="Dave" #optional
description='''
Remember early Tinkers Contruct with the fancy little Metal Bushes?

Now it comes alive with the new Bushes in Minecraft. Have Fun!
'''



[[dependencies.metalbushesmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[38,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.metalbushesmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
